package Deliveryman;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jing
 */
public class Deliveryman extends javax.swing.JFrame {
    
    /**
     * Creates new form Deliveryman
     */
    public Deliveryman() {
        initComponents();
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JID1 = new javax.swing.JLabel();
        JID3 = new javax.swing.JLabel();
        JID2 = new javax.swing.JLabel();
        JID4 = new javax.swing.JLabel();
        JID5 = new javax.swing.JLabel();
        JID6 = new javax.swing.JLabel();
        JNAME1 = new javax.swing.JLabel();
        JNAME2 = new javax.swing.JLabel();
        JNAME3 = new javax.swing.JLabel();
        JNAME4 = new javax.swing.JLabel();
        JNAME5 = new javax.swing.JLabel();
        JNAME6 = new javax.swing.JLabel();
        JPHONE1 = new javax.swing.JLabel();
        JPHONE2 = new javax.swing.JLabel();
        JPHONE6 = new javax.swing.JLabel();
        JPHONE3 = new javax.swing.JLabel();
        JPHONE4 = new javax.swing.JLabel();
        JPHONE5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JCHECK1 = new javax.swing.JComboBox();
        JCHECK2 = new javax.swing.JComboBox();
        JCHECK3 = new javax.swing.JComboBox();
        JCHECK4 = new javax.swing.JComboBox();
        JCHECK5 = new javax.swing.JComboBox();
        JCHECK6 = new javax.swing.JComboBox();
        JSTATUS1 = new javax.swing.JLabel();
        JSTATUS2 = new javax.swing.JLabel();
        JSTATUS3 = new javax.swing.JLabel();
        JSTATUS4 = new javax.swing.JLabel();
        JSTATUS5 = new javax.swing.JLabel();
        JSTATUS6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfshow = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff no. ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Staff ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Deliveryman Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PhoneNumber");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Attendance Check In");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("1.)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("2.)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("3.)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("4.)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("6.)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("5.)");

        JID1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JID3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JID2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JID4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JID5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JID6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JNAME6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        JPHONE5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Status Check");

        JCHECK1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK1.setSelectedItem(null);
        JCHECK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCHECK1MouseClicked(evt);
            }
        });
        JCHECK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK1ActionPerformed(evt);
            }
        });

        JCHECK2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK2.setSelectedItem(null);
        JCHECK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK2ActionPerformed(evt);
            }
        });

        JCHECK3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK3.setSelectedItem(null);
        JCHECK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK3ActionPerformed(evt);
            }
        });

        JCHECK4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK4.setSelectedItem(null);
        JCHECK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK4ActionPerformed(evt);
            }
        });

        JCHECK5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK5.setSelectedItem(null);
        JCHECK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK5ActionPerformed(evt);
            }
        });

        JCHECK6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JCHECK6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Check in", "Check Out", "On Leave", "On Duty", " " }));
        JCHECK6.setSelectedItem(null);
        JCHECK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCHECK6ActionPerformed(evt);
            }
        });

        JSTATUS1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS1.setText("Status");
        JSTATUS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS1MouseClicked(evt);
            }
        });

        JSTATUS2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS2.setText("Status");
        JSTATUS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS2MouseClicked(evt);
            }
        });

        JSTATUS3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS3.setText("Status");
        JSTATUS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS3MouseClicked(evt);
            }
        });

        JSTATUS4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS4.setText("Status");
        JSTATUS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS4MouseClicked(evt);
            }
        });

        JSTATUS5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS5.setText("Status");
        JSTATUS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS5MouseClicked(evt);
            }
        });

        JSTATUS6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JSTATUS6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JSTATUS6.setText("Status");
        JSTATUS6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSTATUS6MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Store");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfshow.setColumns(20);
        jtfshow.setRows(5);
        jtfshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtfshow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JID6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JNAME1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addComponent(JNAME2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                    .addComponent(JNAME3, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(JNAME4, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(JNAME5, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(JNAME6, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPHONE4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPHONE2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPHONE3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPHONE1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPHONE6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPHONE5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCHECK1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCHECK2, 0, 218, Short.MAX_VALUE)
                            .addComponent(JCHECK3, 0, 218, Short.MAX_VALUE)
                            .addComponent(JCHECK4, 0, 218, Short.MAX_VALUE)
                            .addComponent(JCHECK5, 0, 218, Short.MAX_VALUE)
                            .addComponent(JCHECK6, 0, 218, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JSTATUS1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSTATUS2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSTATUS3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSTATUS4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSTATUS5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JSTATUS6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(306, 306, 306)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(JPHONE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(JCHECK1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(JPHONE2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(JCHECK2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(JSTATUS2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JPHONE3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(JCHECK3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(JSTATUS3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JPHONE4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(JCHECK4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JSTATUS4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JPHONE5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JCHECK5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JSTATUS5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JSTATUS1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(JPHONE6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCHECK6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JSTATUS6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(JID1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(JNAME1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(JID2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(JNAME2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JID3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(JNAME3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JID4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JNAME4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JID5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JNAME5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JID6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JNAME6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 156, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        double staffid;
        staffid=  1001;
        String stfid1 =String.format("%.0f", staffid+1);
        JID1.setText(stfid1);
        
        String stfid2=String.format("%.0f", staffid+2);
        JID2.setText(stfid2);
        
        String stfid3=String.format("%.0f",staffid+3 );
        JID3.setText(stfid3);
        
        String stfid4=String.format("%.0f", staffid+4);
        JID4.setText(stfid4);
        
        String stfid5=String.format("%.0f", staffid+5);
        JID5.setText(stfid5);
        
        String stfid6=String.format("%.0f",staffid+6);
        JID6.setText(stfid6);
        
        JNAME1.setText("Aaron");
        JNAME2.setText("Andrew");
        JNAME3.setText("Ervin Lim");
        JNAME4.setText("Tommy");
        JNAME5.setText("Jimmy");
        JNAME6.setText("WhyMe");
        
        JPHONE1.setText("016-1234567");
        JPHONE2.setText("016-9876501");
        JPHONE3.setText("012-9876320");
        JPHONE4.setText("016-1239211");
        JPHONE5.setText("011-1231231");
        JPHONE6.setText("016-9876321");
    }//GEN-LAST:event_formWindowActivated

    private void JSTATUS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS1MouseClicked

    }//GEN-LAST:event_JSTATUS1MouseClicked

    private void JSTATUS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS2MouseClicked
 
    }//GEN-LAST:event_JSTATUS2MouseClicked

    private void JSTATUS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS3MouseClicked

    }//GEN-LAST:event_JSTATUS3MouseClicked

    private void JSTATUS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS4MouseClicked

    }//GEN-LAST:event_JSTATUS4MouseClicked

    private void JSTATUS5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS5MouseClicked
     
    }//GEN-LAST:event_JSTATUS5MouseClicked

    private void JSTATUS6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSTATUS6MouseClicked
 
    }//GEN-LAST:event_JSTATUS6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String button1 =(String)JSTATUS1.getText();
             String button2 =(String)JSTATUS2.getText();
              String button3 =(String)JSTATUS3.getText();
               String button4 =(String)JSTATUS4.getText();
                String button5 =(String)JSTATUS5.getText();
                 String button6 =(String)JSTATUS6.getText();
          if(JCHECK1.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK1.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK1.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave ");      
                    }else if(JCHECK1.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty ");  
                    }
                      else  if(JCHECK2.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK2.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK2.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave "  );      
                    }else if(JCHECK2.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty "  );  
                    }
                    else  if(JCHECK3.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK3.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK3.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave "  );      
                    }else if(JCHECK3.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty "  );  
                    }
                     else  if(JCHECK4.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK4.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK4.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave "  );      
                    }else if(JCHECK1.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty "  );  
                    }
             else  if(JCHECK5.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK5.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK5.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave "  );      
                    }else if(JCHECK5.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty "  );  
                    }
          else  if(JCHECK6.getSelectedIndex()==0){
            jtfshow.setText("Your have been checked in "  );}
            else if(JCHECK6.getSelectedIndex()==1){
            jtfshow.setText("Your had check out "  );      
                    
                    }else if(JCHECK6.getSelectedIndex()==2){
                jtfshow.setText("Your status had changed on leave "  );      
                    }else if(JCHECK6.getSelectedIndex()==3){
                        jtfshow.setText("Your status had changed on duty "  );  
                    }else{
                    jtfshow.setText("");
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfshowMouseClicked
           
    }//GEN-LAST:event_jtfshowMouseClicked

    private void JCHECK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCHECK1MouseClicked
       
    }//GEN-LAST:event_JCHECK1MouseClicked

    private void JCHECK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK1ActionPerformed
                  String status1=(String)JCHECK1.getSelectedItem();
            JSTATUS1.setText(status1);
    }//GEN-LAST:event_JCHECK1ActionPerformed

    private void JCHECK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK2ActionPerformed
                      String status2=(String)JCHECK2.getSelectedItem();
        JSTATUS2.setText(status2);
    }//GEN-LAST:event_JCHECK2ActionPerformed

    private void JCHECK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK3ActionPerformed
                          String status3=(String)JCHECK3.getSelectedItem();
        JSTATUS3.setText(status3);
    }//GEN-LAST:event_JCHECK3ActionPerformed

    private void JCHECK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK4ActionPerformed
                       String status4=(String)JCHECK4.getSelectedItem();
        JSTATUS4.setText(status4);
    }//GEN-LAST:event_JCHECK4ActionPerformed

    private void JCHECK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK5ActionPerformed
              String status5=(String)JCHECK5.getSelectedItem();
             JSTATUS5.setText(status5);

    }//GEN-LAST:event_JCHECK5ActionPerformed

    private void JCHECK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCHECK6ActionPerformed
                     String status6=(String)JCHECK6.getSelectedItem();
        JSTATUS6.setText(status6);
    }//GEN-LAST:event_JCHECK6ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {

            
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deliveryman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Deliveryman().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JCHECK1;
    private javax.swing.JComboBox JCHECK2;
    private javax.swing.JComboBox JCHECK3;
    private javax.swing.JComboBox JCHECK4;
    private javax.swing.JComboBox JCHECK5;
    private javax.swing.JComboBox JCHECK6;
    private javax.swing.JLabel JID1;
    private javax.swing.JLabel JID2;
    private javax.swing.JLabel JID3;
    private javax.swing.JLabel JID4;
    private javax.swing.JLabel JID5;
    private javax.swing.JLabel JID6;
    private javax.swing.JLabel JNAME1;
    private javax.swing.JLabel JNAME2;
    private javax.swing.JLabel JNAME3;
    private javax.swing.JLabel JNAME4;
    private javax.swing.JLabel JNAME5;
    private javax.swing.JLabel JNAME6;
    private javax.swing.JLabel JPHONE1;
    private javax.swing.JLabel JPHONE2;
    private javax.swing.JLabel JPHONE3;
    private javax.swing.JLabel JPHONE4;
    private javax.swing.JLabel JPHONE5;
    private javax.swing.JLabel JPHONE6;
    private javax.swing.JLabel JSTATUS1;
    private javax.swing.JLabel JSTATUS2;
    private javax.swing.JLabel JSTATUS3;
    private javax.swing.JLabel JSTATUS4;
    private javax.swing.JLabel JSTATUS5;
    private javax.swing.JLabel JSTATUS6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtfshow;
    // End of variables declaration//GEN-END:variables




}
